movie_project/movie_app/urls.py
from django.urls import path
from . import views
app_name = 'movie_app'
urlpatterns = [
    path('', views.index, name="index"),
    path('movie/<int:movie_id>/', views.Details, name='Details'),
    path('add/', views.Add_Movie, name='Add_Movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete')

]

movie_project/movie_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_project/movie_app/models.py
from django.db import models


class Movie(models.Model):
    name = models.CharField(max_length=100)
    desc = models.TextField()
    year = models.IntegerField()
    short_desc = models.TextField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movie_project/movie_app/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movie_project/movie_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from movie_app.forms import MovieForm
from movie_app.models import Movie
from django.shortcuts import render


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)


def Details(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "details.html", {'movie': movie})


def Add_Movie(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        short_desc = request.POST.get('short_desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, short_desc=short_desc, img=img)
        movie.save()

    return render(request, 'Add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
        if request.method == "POST":
            movie = Movie.objects.get(id=id)
            movie.delete()
            return redirect('/')
        return render(request, 'delete.html')

movie_project/templates/Add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #a7d397;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
        input {
            width: 100%;
            margin-bottom: 15px;
            padding: 10px;
            border: 1px solid #ccc;
            border-radius: 3px;
            font-size: 16px;
        }
        input[type="file"] {
            border: none;
            background-color: #f7f7f7;
        }
        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 3px;
            font-size: 16px;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" name="name" placeholder="Enter the movie name">
        <input type="text" name="short_desc" placeholder="Enter the movie short description">
        <input type="text" name="desc" placeholder="Enter the movie description">
        <input type="text" name="year" placeholder="Enter the movie year">
        <input type="file" name="img">
        <input type="submit" value="Submit">
    </form>
</body>
</html>

movie_project/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Confirmation</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: black;
            text-align: center;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 3px;
            font-size: 16px;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure?</p>
        <input type="submit" value="Confirm">
    </form>
</body>
</html>

movie_project/templates/details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Details</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'details.css' %}">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .container {
            text-align: center;
            padding: 20px;
            background-color: #fff;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            margin-top: 20px;
        }
        .movie-img {
            max-width: 100%;
            height: auto;
        }
        h1 {
            font-size: 36px;
            margin-top: 20px;
        }
        p {
            font-size: 18px;
        }
        .btn {
            font-size: 24px;
            font-weight: bold;
            margin: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <img class="movie-img" src="{{ movie.img.url }}" alt="Movie Image">
        <h1>{{ movie.name }}</h1>
        <p>{{ movie.desc }}</p>
        <a href="{% url 'movie_app:update' movie.id %}" class="btn btn-success" style="color: black;">Update</a>
        <a href="{% url 'movie_app:delete' movie.id %}" class="btn btn-danger" style="color: black;">Delete</a>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>

movie_project/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #B15EFF;
            text-align: center;
        }
        form {
            max-width: 400px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
            border-radius: 5px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        }
        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            padding: 10px 20px;
            border-radius: 3px;
            font-size: 16px;
            cursor: pointer;
        }
        input[type="submit"]:hover {
            background-color: #0056b3;
        }
        p {
            text-align: left;
            font-size: 18px;
        }
    </style>
</head>
<body>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

movie_project/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'index.css' %}">

    <style>
        /* Custom styles for alignment and aesthetics */
        body {
            background-color: #dde6ed;
        }
        .navbar {
            background-color: #343a40;
        }
        .navbar a {
            color: white;
            font-weight: bold;
        }
        .navbar .navbar-brand {
            text-align: center;
            color: white;
            font-size: 28px;
            font-weight: bold;
        }
        .container {
            padding: 20px;
        }
        .card {
            margin: 10px;
            box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
            background-color: #fff;
        }
        .card-title {
            font-size: 24px;
            color: #333;
            text-align: center;
            font-weight: bold;
        }
        .card-subtitle {
            font-size: 20px;
            color: #666;
            text-align: center;
            font-weight: bold;
        }
    </style>
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <a href="{% url 'movie_app:Add_Movie' %}" class="btn btn-dark">Add New Movies</a>
            <a class="navbar-brand">MOVIE HUB</a>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container">

<div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
   <div class="carousel-inner">
      <div class="carousel-item active" data-bs-interval="10000">
        <img src="{% static 'images/front1.jpg' %}" class="d-block w-100" alt="...">
         </div>
           <div class="carousel-item" data-bs-interval="2000">
             <img src="{% static 'images/demo2.jpg' %}" class="d-block w-100" alt="...">
                </div>
                    <div class="carousel-item">
                        <img src="{% static 'images/front2.jpg' %}" class="d-block w-100" alt="...">
                            </div>
                                 </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
        <div class="row">
            {% for i in movie_list %}
            <div class="col-lg-4 col-md-4 col-sm-4">
                <div class="card" style="width: 100%;">
                    <img src="{{ i.img.url }}" width="420"  height="370" class="card-img-top" alt="Place Image">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <h5 class="card-subtitle">{{ i.short_desc }}</h5>
                        <a href="{% url 'movie_app:Details' i.id %}" class="btn btn-dark">More</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
</body>
</html>